---
title: "Big Data Bowl Visualizations"
output: html_document
date: "2024-04-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
library(tidyverse)
library(ggplot2)
library(knitr)
library(kableExtra)
library(flextable)
library(ftExtra)
library(latex2exp)
```

```{r read_in_data}
games = read_csv("games.csv")
full_dict = read_csv("full_dictionary_54.csv")
games_dict = read_csv("games_dictionary_54.csv")
full_dict44 = read_csv("full_dictionary_44.csv")
games_dict44 = read_csv("games_dictionary_44.csv")
full_dict64 = read_csv("full_dictionary_64.csv")
games_dict64 = read_csv("games_dictionary_64.csv")
full_dict_c = read_csv("full_dictionary_constant.csv")
games_dict_c = read_csv("games_dictionary_constant.csv")
ex_dict = read_csv("example_dictionary.csv")

full_dict$radius = "1.25yd Varying"
full_dict44$radius = "1.0yd Varying"
full_dict64$radius = "1.5yd Varying"
full_dict_c$radius = "1.5yd Constant"
sens_analysis_data = bind_rows(full_dict44, full_dict, full_dict64, full_dict_c)

games_dict$radius = "1.25yd Varying"
games_dict44$radius = "1.0yd Varying"
games_dict64$radius = "1.5yd Varying"
games_dict_c$radius = "1.5yd Constant"
sens_analysis_team = bind_rows(games_dict44, games_dict, games_dict64, games_dict_c)
```


## An example play

```{r}
ft1 = ex_dict %>%
  select(-c(`...1`, Player_ID, Team, Position)) %>%
  select(index, Player_Name, Opportunities, Contains) %>%
  rename(Opportunity = Opportunities, Contain = Contains) %>%
  arrange(Opportunity, Contain) %>%
  flextable() %>%
  set_header_labels(index = "Index", Player_Name = "Player Name", 
                    Opportunity = "Tackle Opportunity", 
                    Contain = "Tackle Containment") %>%
  add_header_row(values = "TOCQ_X Output of Example Play", colwidths = 4)

gr1 = gen_grob(ft1, fit = "auto", scaling = "full", just = "center")
gr1_dim = dim(gr1)

ragg::agg_png(filename = "Figures And Tables/ExamplePlay.png", 
              width = 2*gr1_dim$width,
              height = 2*gr1_dim$height, units = "in"
              )
plot(gr1)
dev.off()

ft1
```

## Sensitivity Analysis (Density comparison of Player TOCQ and N)

```{r}
sens_analysis_data %>%
  select(index, Opportunities, Contains, radius) %>%
  mutate(TOCQ = Contains / Opportunities) %>%
  ggplot() +
  geom_density(aes(x = TOCQ, group = radius, fill = radius, color = radius),
               alpha = 0.5) +
  scale_fill_manual(values = c("1.0yd Varying" = "darkturquoise",
                               "1.25yd Varying" = "darkorange2",
                               "1.5yd Varying" = "darkgoldenrod1",
                               "1.5yd Constant" = "darkolivegreen3")) +
  scale_color_manual(values = c("1.0yd Varying" = "darkturquoise",
                               "1.25yd Varying" = "darkorange2",
                               "1.5yd Varying" = "darkgoldenrod1",
                               "1.5yd Constant" = "darkolivegreen3")) +
  theme_minimal() +
  labs(x = TeX(r"( Player Half-Season $TOCQ_X$ )"),
       y = "Density",
       group = "Radius",
       fill = "Radius",
       color = "Radius",
       title = TeX(r"( Sensitivity of $TOCQ_X$ Density in Varying Tackle Zone Radius )"))

ggsave("Figures And Tables/SensitivityAnalysisTOCQ.png")
```
```{r}
sens_analysis_data %>%
  select(index, Opportunities, Contains, radius) %>%
  mutate(TOCQ = Contains / Opportunities) %>%
  ggplot() +
  geom_density(aes(x = Opportunities, group = radius, 
                   fill = radius, color = radius),
               alpha = 0.5) +
  scale_fill_manual(values = c("1.0yd Varying" = "darkturquoise",
                               "1.25yd Varying" = "darkorange2",
                               "1.5yd Varying" = "darkgoldenrod1",
                               "1.5yd Constant" = "darkolivegreen3")) +
  scale_color_manual(values = c("1.0yd Varying" = "darkturquoise",
                               "1.25yd Varying" = "darkorange2",
                               "1.5yd Varying" = "darkgoldenrod1",
                               "1.5yd Constant" = "darkolivegreen3")) +
  theme_minimal() +
  labs(x = "Player Half-Season Tackle Opportunities",
       y = "Density",
       group = "Radius",
       fill = "Radius",
       color = "Radius",
       title = "Sensitivity of Tackle Opportunities in Varying Tackle Zone Radius")

ggsave("Figures And Tables/SensitivityAnalysisN.png")
```
### Sensitivity Analysis Table

```{r}
ft = sens_analysis_data %>%
  select(index, Opportunities, Contains, radius) %>%
  mutate(TOCQ = Contains / Opportunities) %>%
  replace_na(list(TOCQ = 0)) %>%
  group_by(radius) %>%
  summarize(mean_tocq = mean(TOCQ),
            se_tocq = sqrt(var(TOCQ)),
            mean_n = mean(Opportunities),
            se_n = sqrt(var(Opportunities))) %>%
  flextable() %>%
  set_header_labels(radius = "Radius", mean_tocq = "Mean TOCQ_X", 
                    se_tocq = "SE TOCQ_X", mean_n = "Mean Player Opportunities",
                    se_n = "SE Player Opportunities") %>%
  empty_blanks() %>%
  add_header_row(values = "Mean and SE of TOCQ_X score and opportunity with varying radius", 
                 colwidths = 5)


gr = gen_grob(ft, fit = "auto", scaling = "full", just = "center")
gr_dim = dim(gr)

ragg::agg_png(filename = "Figures And Tables/SensitivityTable.png", 
              width = 2*gr_dim$width,
              height = 2*gr_dim$height, units = "in"
              )
plot(gr)
dev.off()

```

```{r}
ft = sens_analysis_team %>%
  group_by(radius, game, Team) %>%
  summarize(team_contains = sum(Contains),
            team_opps = sum(Opportunities)) %>%
  mutate(TOCQ = team_contains / team_opps,
         radius = radius) %>%
  replace_na(list(TOCQ = 0)) %>%
  group_by(radius) %>%
  summarize(mean_tocq = mean(TOCQ),
            se_tocq = sqrt(var(TOCQ)),
            mean_n = mean(team_opps),
            se_n = sqrt(var(team_opps))) %>%
  flextable() %>%
  set_header_labels(radius = "Radius", mean_tocq = "Mean TOCQ_T", 
                    se_tocq = "SE TOCQ_T", mean_n = "Mean Team Opportunities",
                    se_n = "SE Team Opportunities") %>%
  empty_blanks() %>%
  add_header_row(values = "Mean and SE of TOCQ_T score and opportunity with varying radius", 
                 colwidths = 5)


gr = gen_grob(ft, fit = "auto", scaling = "full", just = "center")
gr_dim = dim(gr)

ragg::agg_png(filename = "Figures And Tables/SensitivityTableTeam.png", 
              width = 2*gr_dim$width,
              height = 2*gr_dim$height, units = "in"
              )
plot(gr)
dev.off()

```


## Top and Bottom 10 individual game scores

```{r}
top10 = games_dict %>%
  filter(Opportunities > 10) %>%
  mutate(TOCQ_X = Contains / Opportunities) %>%
  left_join(games, by = join_by(game == gameId)) %>%
  rename(Week = week) %>%
  select(Week, Player_Name, Team, Position, TOCQ_X) %>%
  arrange(desc(TOCQ_X)) %>%
  slice_head(n = 10)

bottom10 = games_dict %>%
  filter(Opportunities > 10) %>%
  mutate(TOCQ_X = Contains / Opportunities) %>%
  left_join(games, by = join_by(game == gameId)) %>%
  rename(Week = week) %>%
  select(Week, Player_Name, Team, Position, TOCQ_X) %>%
  rename(bot_week = Week, bot_name = Player_Name, bot_team = Team, 
         bot_pos = Position, bot_tocq = TOCQ_X) %>%
  arrange(bot_tocq) %>%
  slice_head(n = 10)

pair_names = colnames(cbind(top10, bottom10))

ft2 = cbind(top10, bottom10) %>%
  flextable(col_keys = c(pair_names[1:5], "col1", pair_names[6:10])) %>%
  set_header_labels(Player_Name = "Player Name", 
                    bot_week = "Week", bot_name = "Player Name", 
    bot_team = "Team", bot_pos = "Position",
    bot_tocq = "TOCQ_X" ) %>%
  width(j = "col1", width = .2) |> 
  empty_blanks() %>%
  add_header_row(values = c("Top 10 Individual Games", 
                            "", 
                            "Bottom 10 Individual Games"), 
                 colwidths = c(5, 1, 5)) %>%
  add_header_row(values = "Individual TOCQ_X Games (Min 10 Opportunities)", 
                 colwidths = 11)

gr2 = gen_grob(ft2, fit = "auto", scaling = "full", just = "center")
gr2_dim = dim(gr2)

ragg::agg_png(filename = "Figures And Tables/GamePlayerScores.png", 
              width = 2*gr2_dim$width,
              height = 2*gr2_dim$height, units = "in"
              )
plot(gr2)
dev.off()

ft2
```


## Top and Bottom 10 half season scores

```{r}
top10 = full_dict %>%
  filter(Opportunities > 30) %>%
  mutate(TOCQ_X = Contains / Opportunities) %>%
  select(Player_Name, Team, Position, TOCQ_X) %>%
  arrange(desc(TOCQ_X)) %>%
  slice_head(n = 10)

bottom10 = full_dict %>%
  filter(Opportunities > 30) %>%
  mutate(TOCQ_X = Contains / Opportunities) %>%
  select(Player_Name, Team, Position, TOCQ_X) %>%
  rename(bot_name = Player_Name, bot_team = Team, 
         bot_pos = Position, bot_tocq = TOCQ_X) %>%
  arrange(bot_tocq) %>%
  slice_head(n = 10)

pair_names = colnames(cbind(top10, bottom10))

ft3 = cbind(top10, bottom10) %>%
  flextable(col_keys = c(pair_names[1:4], "col1", pair_names[5:8])) %>%
  set_header_labels(Player_Name = "Player Name", bot_name = "Player Name", 
    bot_team = "Team", bot_pos = "Position",
    bot_tocq = "TOCQ_X" ) %>%
  width(j = "col1", width = .2) |> 
  empty_blanks() %>%
  add_header_row(values = c("Top 10 Individual Players", 
                            "", 
                            "Bottom 10 Individual Players"), 
                 colwidths = c(4, 1, 4)) %>%
  add_header_row(values = "Half Season TOCQ_X Scores (minimum 30 Opportunites)",
                 colwidths = 9)

gr3 = gen_grob(ft3, fit = "auto", scaling = "full", just = "center")
gr3_dim = dim(gr3)

ragg::agg_png(filename = "Figures And Tables/HalfSeasonPlayerScores.png", 
              width = 2*gr3_dim$width,
              height = 2*gr3_dim$height, units = "in"
              )
plot(gr3)
dev.off()

ft3
```

## Box plot by position group

```{r}
pos_levels = full_dict %>%
  filter(Opportunities > 10, Position != "DB") %>%
  mutate(TOCQ_X = Contains / Opportunities, 
         Pos_group = case_when(Position %in% c("CB", "FS", "SS") ~ "Secondary",
                               Position %in% c("ILB", "MLB", "OLB") ~ "Linebacker",
                               Position %in% c("DT", "NT", "DE") ~ "Defensive Line")) %>%
  with(reorder(Position, TOCQ_X, median)) %>%
  levels()

full_dict %>%
  filter(Opportunities > 10, Position != "DB") %>%
  mutate(TOCQ_X = Contains / Opportunities, 
         Pos_group = case_when(Position %in% c("CB", "FS", "SS") ~ "Secondary",
                               Position %in% c("ILB", "MLB", "OLB") ~ "Linebacker",
                               Position %in% c("DT", "NT", "DE") ~ "Defensive Line")) %>%
  mutate(Position = factor(Position, levels = pos_levels)) %>%
  ggplot(aes(x = Position, y = TOCQ_X, fill = Pos_group)) +
  geom_boxplot() +
  theme_minimal() +
  labs(title = TeX(r"( Half Season $TOCQ_X$ score by position group )"),
       x = TeX(r"( $TOCQ_X$ )"),
       fill = "Position Group")

ggsave("Figures And Tables/HalfSeasonPositionGroup.png")
```

## Top and Bottom 10 Single Game TOCQ_T scores

```{r}
top10team = games_dict %>%
  group_by(game, Team) %>%
  summarize(team_contains = sum(Contains),
            team_opps = sum(Opportunities)) %>%
  mutate(TOCQ_T = team_contains / team_opps,
         gameId = game) %>%
  left_join(games, by = join_by(gameId)) %>%
  mutate(Opponent = case_when(Team == homeTeamAbbr ~ visitorTeamAbbr,
                              Team == visitorTeamAbbr ~ homeTeamAbbr)) %>%
  ungroup() %>%
  select(Team, week, Opponent, TOCQ_T) %>%
  rename(Week = week) %>%
  arrange(desc(TOCQ_T)) %>%
  slice_head(n = 10)

bottom10team = games_dict %>%
  group_by(game, Team) %>%
  summarize(team_contains = sum(Contains),
            team_opps = sum(Opportunities)) %>%
  mutate(TOCQ_T = team_contains / team_opps,
         gameId = game) %>%
  left_join(games, by = join_by(gameId)) %>%
  mutate(Opponent = case_when(Team == homeTeamAbbr ~ visitorTeamAbbr,
                              Team == visitorTeamAbbr ~ homeTeamAbbr)) %>%
  ungroup() %>%
  select(Team, week, Opponent, TOCQ_T) %>%
  rename(bot_team = Team, bot_week = week, 
         bot_opp = Opponent, bot_tocq = TOCQ_T) %>%
  arrange(bot_tocq) %>%
  slice_head(n = 10) 

pair_names = colnames(cbind(top10team, bottom10team))

ft5 = cbind(top10team, bottom10team) %>%
  flextable(col_keys = c(pair_names[1:4], "col1", pair_names[5:8])) %>%
  set_header_labels(bot_week = "Week", 
    bot_team = "Team", bot_opp = "Opponent",
    bot_tocq = "TOCQ_T" ) %>%
  width(j = "col1", width = .2) |> 
  empty_blanks() %>%
  add_header_row(values = c("Top 10 Team Games", 
                            "", 
                            "Bottom 10 Team Games"), 
                 colwidths = c(4, 1, 4)) %>%
  add_header_row(values = "Team TOCQ_T Single Games", colwidths = 9)

gr5 = gen_grob(ft5, fit = "auto", scaling = "full", just = "center")
gr5_dim = dim(gr5)

ragg::agg_png(filename = "Figures And Tables/GameTeamScores.png", 
              width = 2*gr5_dim$width,
              height = 2*gr5_dim$height, units = "in"
              )
plot(gr5)
dev.off()

ft5
```

## Half Season TOCQ_T team bargraph

```{r}
games_dict %>%
  group_by(game, Team) %>%
  summarize(team_contains = sum(Contains),
            team_opps = sum(Opportunities), .groups = "drop") %>%
  mutate(TOCQ_T = team_contains / team_opps) %>%
  ungroup() %>%
  group_by(Team) %>%
  summarize(TOCQ_T = mean(TOCQ_T)) %>%
  ungroup() %>%
  add_row(Team = "NFL", TOCQ_T = mean(pull(., TOCQ_T))) %>%
  mutate(avg = case_when(TOCQ_T > mean(pull(., TOCQ_T)) ~ "Above League Average",
                         TOCQ_T < mean(pull(., TOCQ_T)) ~ "Below League Average",
                         TRUE ~ "League Average"),
         avg = factor(avg, levels = c("Above League Average", 
                                      "League Average",
                                      "Below League Average"))) %>%
  arrange(desc(TOCQ_T)) %>%
  ggplot(aes(y = fct_reorder(Team, TOCQ_T), x = TOCQ_T, fill = avg)) +
  geom_col() +
  scale_fill_manual(values = c("darkgreen", "black", "purple")) +
  theme_minimal() +
  labs(title = TeX(r"( Half Season Mean $TOCQ_T$ relative to NFL Average )"),
       y= "Team",
       x = TeX(r"( Mean $TOCQ_T$ )"),
       fill = element_blank())

ggsave("Figures And Tables/HalfSeasonTeam.png")
```

## Individual Position Group by team heatmap

```{r}
full_dict %>%
  filter(!(Position %in% c("RB", "WR", "FB"))) %>%
  mutate(Pos_group = case_when(Position %in% c("CB", "FS", "SS", "DB") ~ "Secondary",
                               Position %in% c("ILB", "MLB", "OLB") ~ "Linebacker",
                               Position %in% c("DT", "NT", "DE") ~ "Defensive Line")) %>%
  group_by(Team, Pos_group) %>%
  summarize(pos_group_contains = sum(Contains),
            pos_group_opps = sum(Opportunities), .groups = "drop") %>%
  mutate(TOCQ_TP = pos_group_contains / pos_group_opps) %>%
  group_by(Pos_group) %>%
  mutate(TOCQTP = TOCQ_TP / mean(TOCQ_TP)) %>%
  ggplot(aes(x = Pos_group, y = Team, fill = TOCQTP)) +
  scale_fill_gradient2(low = "darkred", mid = "white", high = "royalblue3",
                       midpoint = 1) +
  geom_tile() +
  theme_minimal() + 
  labs(title = TeX(r"( Position Group Mean $TOCQ_T$ Relative to League Average )"),
       x = "Position Group",
       fill = TeX(r"( $TOCQ_T$ Proportion )"))

ggsave("Figures And Tables/HalfSeasonTeamPositionGroup.png")
```

